name: Build Checks (pytest)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: etherea-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: CI-safe pytest
    runs-on: ubuntu-latest
    env:
      ETHEREA_CI: "1"
      PYTHONUNBUFFERED: "1"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build EXE
      run: pyinstaller etherea.spec --noconfirm --clean
    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EthereaOS_Windows_Fresh
        path: |
          dist/EthereaOS.exe
          dist/EthereaOS/EthereaOS.exe
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest

      - name: Run pytest (CI-safe)
        run: |
          pytest -q
